name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
      - name: code checkout
        uses: actions/checkout@v2
      - name: running sitespeed.io container with arguments and optional Docker options
        run: docker run -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:38.2.0 https://kuznecoff.github.io/webmap-sdk-speed-test/mapgl/mapgl-zoom-11.html --outputFolder output --video --budget.configPath .github/budget.json -n 1 
